embed_images: datauri
template_function: _.template
compress_assets: off
gzip_assets: off

javascripts:
  viewer:
    - public/javascripts/DV/vendor/jquery-1.5.1.js
    - public/javascripts/DV/vendor/jquery-ui-1.8.1.custom.min.js
    - public/javascripts/DV/vendor/underscore.js
    - public/javascripts/DV/vendor/jquery.acceptInput.js
    - public/javascripts/DV/vendor/jquery.placeholder.js
    - public/javascripts/DV/lib/initializer.js
    - public/javascripts/DV/lib/*.js
    - public/javascripts/DV/schema/*.js
    - public/javascripts/DV/elements/*.js
    - public/javascripts/DV/models/*.js
    - public/javascripts/DV/events/events.js
    - public/javascripts/DV/events/View*.js
    - public/javascripts/DV/events/*.js
    - public/javascripts/DV/helpers/helpers.js
    - public/javascripts/DV/helpers/*.js
    - public/javascripts/DV/states/*.js
    - public/javascripts/DV/controllers/*.js
    - public/annotator/vendor/jquery.js
    - public/annotator/js/util.js
    - public/annotator/js/console.js
    - public/annotator/js/class.js
    - public/annotator/js/range.js
    - public/annotator/js/annotator.js
    - public/annotator/js/widget.js
    - public/annotator/js/editor.js
    - public/annotator/js/viewer.js
    - public/annotator/js/notification.js
    - public/annotator/js/xpath.js
    - public/annotator/js/plugin/store.js
    - public/javascripts/DV/views/*.jst

  templates:
    - public/javascripts/DV/views/*.jst

stylesheets:
  viewer:
    - public/stylesheets/DV/components/reset.css
    - public/stylesheets/DV/components/structure.css
    - public/stylesheets/DV/components/ui.css
    - public/stylesheets/DV/components/*.css
    - public/stylesheets/DV/themes/plain.css
    - public/annotator/css/annotator.min.css
    - public/stylesheets/annotator_fix.css

  print:
    - public/stylesheets/DV/print.css

